services:
  prometheus:
      ports:
        - 9090:9090

  fake:
    build:
      context: .
      dockerfile: fake_exporters/Dockerfile
    restart: unless-stopped
    volumes:
      - $PWD/fake_power/:/usr/src/app:ro
    expose:
      - 8080
    ports:
      - "8080:8080"