global:
  scrape_interval: 10s 

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]
 
  - job_name: "neil"
    static_configs:
    - targets: ["dust.sdsc.edu:9100"]

  - job_name: "craig"
    static_configs:
    - targets: ["192.31.21.251:9100"]

  - job_name: "evans"
    static_configs:
    - targets: ["192.31.21.253:9100"]



  - job_name: power_exporter
    scrape_interval: 3s
    scrape_timeout: 2s
    honor_labels: true
    metrics_path: /probe
    static_configs:
      - targets:
        - http://192.168.4.4/api 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: geist-exporter:7979

  - job_name: competetion_power_limit
    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true
    metrics_path: /probe
    static_configs:
      - targets:
        - http://host.docker.internal:8080/power.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: competetion-power-exporter:7979
    

  # This is to measure the json exporter application
  - job_name: json-geist-application
    static_configs:
      - targets:
        - geist-exporter:7979
  
