# This Ansible file configures Bunny, the cluster monitoring platform, running on a Raspberry Pi with Ubuntu.
#
# For now, this just installs Caddy, a reverse proxy that allows for easy HTTPS over the internet.
---
    - hosts: bunny
      become: yes
      vars:
        # The config here says "for any requests for bunny.sdsc.edu or its subpaths, redirect to port 3000"
        # We just need to run Grafana on that port in our Docker Compose configuration.
        caddy_config: |
          bunny.sdsc.edu {
            reverse_proxy 127.0.0.1:3000
          }
    
      roles:
        # Install the Caddy Ansible role, which automatically updates and configures it.
        - caddy_ansible.caddy_ansible
    